CREATE DATABASE opm202403;
--/Users/tiangeng/Public/data/opm_mar2024
/*TABLES*/
CREATE TABLE fact(
	AGYSUB VARCHAR(4),
	LOC VARCHAR(2),
	AGELVL VARCHAR(1),
	EDLVL VARCHAR(2),
	GSEGRD VARCHAR(2),
	LOSLVL VARCHAR(1),
	OCC VARCHAR(4),
	PATCO VARCHAR(1),
	PP VARCHAR(2),
	PPGRD VARCHAR(5),
	SALLVL VARCHAR(2),
	STEMOCC VARCHAR(4),
	SUPERVIS VARCHAR(1),
	TOA VARCHAR(2),
	WORKSCH VARCHAR(1),
	WORKSTAT VARCHAR(1),
	DATECODE VARCHAR(6),
	EMPLOYMENT VARCHAR(1),
	SALARY NUMERIC(8,1),
	LOS NUMERIC(3,1)
);

COPY fact FROM '/Users/tiangeng/Public/data/opm_mar2024/FACTDATA_MAR2024.TXT'
WITH (FORMAT CSV, HEADER);

/*EXPLORE TABLE*/
SELECT * FROM fact LIMIT 10;
SELECT COUNT(*) FROM fact;